# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: local-pvc2
# spec:
#   storageClassName: local-storage-class2
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc2
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      id: mysql-pv2
