# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv2
# spec:
#   storageClassName: local-storage-class2
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /Users/jfoerster008/bootcamp/k8s



apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
  labels:
    type: local
    id: mysql-pv2
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/jfoerster008/bootcamp/k8s
